import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nothing here</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex h-screen w-screen justify-center items-center'>
        <h1>Nothing to see here</h1>
      </main>
    </>
  )
}
